/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class me_terato_Main */

#ifndef _Included_me_terato_Main
#define _Included_me_terato_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     me_terato_Main
 * Method:    getOsName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_me_terato_Main_getOsName
  (JNIEnv *, jobject);

/*
 * Class:     me_terato_Main
 * Method:    operationTwoNumbers
 * Signature: (FF)Lme/terato/Operation;
 */
JNIEXPORT jobject JNICALL Java_me_terato_Main_operationTwoNumbers
  (JNIEnv *, jobject, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
